from dataclasses import dataclass, field
import math as m
from typing import Dict

@dataclass
class VirtualBone:
    head: str
    tail: str
    parent_bone: str
    lengths: list = field(default_factory=list)
    median: float = 0.0
    stdev: float = 0.0
    category: str = ''
    connected: bool = False
    orientation: tuple = (0, 0, 0)
    parent_position: str = 'head'
    bone_x_axis: tuple = (0, 0, 0)
    bone_y_axis: tuple = (0, 0, 0)
    bone_z_axis: tuple = (0, 0, 0)
    rot_limit_min_x: float = 0.0
    rot_limit_max_x: float = 0.0
    rot_limit_min_z: float = 0.0
    rot_limit_max_z: float = 0.0
    has_skelly_part: bool = False
    default_origin: tuple = (0, 0, 0)
    default_length: float = 0.0

virtual_bones: Dict[str, VirtualBone] = {
    'pelvis.R': VirtualBone(
        head='hips_center',
        tail='right_hip',
        parent_bone='pelvis',
        orientation=(0, m.radians(-90), 0),
    ),
    'pelvis.L': VirtualBone(
        head='hips_center',
        tail='left_hip',
        parent_bone='pelvis',
        orientation=(0, m.radians(90), 0),
    ),
    'spine': VirtualBone(
        head='hips_center',
        tail='trunk_center',
        parent_bone='pelvis',
    ),
    'spine.001': VirtualBone(
        head='trunk_center',
        tail='neck_center',
        parent_bone='spine',
        connected=True,
        parent_position='tail',
    ),
    'neck': VirtualBone(
        head='neck_center',
        tail='head_center',
        parent_bone='spine.001',
        connected=True,
        parent_position='tail',
    ),
    'face': VirtualBone(
        head='head_center',
        tail='nose',
        parent_bone='neck',
        connected=True,
        orientation=(m.radians(110), 0, 0),
        parent_position='tail',
    ), # Aux bone from head center to nose tip to align face bones
    'shoulder.R': VirtualBone(
        head='neck_center',
        tail='right_shoulder',
        parent_bone='spine.001',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
    ),
    'shoulder.L': VirtualBone(
        head='neck_center',
        tail='left_shoulder',
        parent_bone='spine.001',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
    ),
    'upper_arm.R': VirtualBone(
        head='right_shoulder',
        tail='right_elbow',
        parent_bone='shoulder.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
    ),
    'upper_arm.L': VirtualBone(
        head='left_shoulder',
        tail='left_elbow',
        parent_bone='shoulder.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
    ),
    'forearm.R': VirtualBone(
        head='right_elbow',
        tail='right_wrist',
        parent_bone='upper_arm.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
    ),
    'forearm.L': VirtualBone(
        head='left_elbow',
        tail='left_wrist',
        parent_bone='upper_arm.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
    ),
    'hand.R': VirtualBone(
        head='right_wrist',
        tail='right_hand_middle',
        parent_bone='forearm.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
    ),
    'hand.L': VirtualBone(
        head='left_wrist',
        tail='left_hand_middle',
        parent_bone='forearm.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
    ),
    'thumb.carpal.R': VirtualBone(
        head='right_hand_wrist',
        tail='right_hand_thumb_cmc',
        category='hands',
        parent_bone='hand.R',
        orientation=(0, m.radians(-90), m.radians(45)),
    ), # Auxiliary bone to align right_hand_thumb_cmc empty
    'thumb.carpal.L': VirtualBone(
        head='left_hand_wrist',
        tail='left_hand_thumb_cmc',
        category='hands',
        parent_bone='hand.L',
        orientation=(0, m.radians(90), m.radians(-45)),
    ), # Auxiliary bone to align the left_hand_thumb_cmc empty
    'thumb.01.R': VirtualBone(
        head='right_hand_thumb_cmc',
        tail='right_hand_thumb_mcp',
        lengths=[],
        median=0,
        stdev=0,
        category='fingers',
        parent_bone='thumb.carpal.R',
        connected=True,
        orientation=(0, m.radians(-90), m.radians(45)),
        parent_position='tail',
        rot_limit_min_x=-50,
        rot_limit_max_x=50,
        rot_limit_min_z=-60,
        rot_limit_max_z=30,
    ),
    'thumb.01.L': VirtualBone(
        head='left_hand_thumb_cmc',
        tail='left_hand_thumb_mcp',
        category='fingers',
        parent_bone='thumb.carpal.L',
        connected=True,
        orientation=(0, m.radians(90), m.radians(-45)),
        parent_position='tail',
        rot_limit_min_x=-50,
        rot_limit_max_x=50,
        rot_limit_min_z=-60,
        rot_limit_max_z=30,
    ),
    'thumb.02.R': VirtualBone(
        head='right_hand_thumb_mcp',
        tail='right_hand_thumb_ip',
        category='fingers',
        parent_bone='thumb.01.R',
        connected=True,
        orientation=(0, m.radians(-90), m.radians(45)),
        parent_position='tail',
        rot_limit_max_x=40,
        rot_limit_min_z=-10,
        rot_limit_max_z=10,
    ),
    'thumb.02.L': VirtualBone(
        head='left_hand_thumb_mcp',
        tail='left_hand_thumb_ip',
        category='fingers',
        parent_bone='thumb.01.L',
        connected=True,
        orientation=(0, m.radians(90), m.radians(-45)),
        parent_position='tail',
        rot_limit_min_x=-40,
        rot_limit_min_z=-10,
        rot_limit_max_z=10,
    ),
    'thumb.03.R': VirtualBone(
        head='right_hand_thumb_ip',
        tail='right_hand_thumb_tip',
        category='fingers',
        parent_bone='thumb.02.R',
        connected=True,
        orientation=(0, m.radians(-90), m.radians(45)),
        parent_position='tail',
        rot_limit_min_x=-10,
        rot_limit_max_x=90,
    ), 
    'thumb.03.L': VirtualBone(
        head='left_hand_thumb_ip',
        tail='left_hand_thumb_tip',
        category='fingers',
        parent_bone='thumb.02.L',
        connected=True,
        orientation=(0, m.radians(90), m.radians(-45)),
        parent_position='tail',
        rot_limit_min_x=-90,
        rot_limit_max_x=10,
    ),
    'palm.01.R': VirtualBone(
        head='right_hand_wrist',
        tail='right_hand_index_finger_mcp',
        category='fingers',
        parent_bone='hand.R',
        connected=False,
        orientation=(0, m.radians(-90), m.radians(17)),
        parent_position='head',
        rot_limit_min_x=-360,
        rot_limit_max_x=360,
        rot_limit_min_z=14,
        rot_limit_max_z=16,
    ),
    'palm.01.L': VirtualBone(
        head='left_hand_wrist',
        tail='left_hand_index_finger_mcp',
        category='fingers',
        parent_bone='hand.L',
        connected=False,
        orientation=(0, m.radians(90), m.radians(-17)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
        rot_limit_min_z=14,
        rot_limit_max_z=16,
    ),
    'f_index.01.R': VirtualBone(
        head='right_hand_index_finger_mcp',
        tail='right_hand_index_finger_pip',
        category='fingers',
        parent_bone='palm.01.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_min_x=-30,
        rot_limit_max_x=60,
        rot_limit_min_z=-30,
        rot_limit_max_z=40,
    ),
    'f_index.01.L': VirtualBone(
        head='left_hand_index_finger_mcp',
        tail='left_hand_index_finger_pip',
        category='fingers',
        parent_bone='palm.01.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
        rot_limit_max_x=30,
        rot_limit_min_z=-30,
        rot_limit_max_z=40,
    ),
    'f_index.02.R': VirtualBone(
        head='right_hand_index_finger_pip',
        tail='right_hand_index_finger_dip',
        category='fingers',
        parent_bone='f_index.01.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_min_x=0,
        rot_limit_max_x=90,
        rot_limit_min_z=0,
        rot_limit_max_z=0,
        has_skelly_part=True,
    ),
    'f_index.02.L': VirtualBone(
        head='left_hand_index_finger_pip',
        tail='left_hand_index_finger_dip',
        category='fingers',
        parent_bone='f_index.01.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-90,
        has_skelly_part=True,
    ),
    'f_index.03.R': VirtualBone(
        head='right_hand_index_finger_dip',
        tail='right_hand_index_finger_tip',
        category='fingers',
        parent_bone='f_index.02.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=60,
        has_skelly_part=True,
    ),
    'f_index.03.L': VirtualBone(
        head='left_hand_index_finger_dip',
        tail='left_hand_index_finger_tip',
        category='fingers',
        parent_bone='f_index.02.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
    ),
    'palm.02.R': VirtualBone(
        head='right_hand_wrist',
        tail='right_hand_middle_finger_mcp',
        category='fingers',
        parent_bone='hand.R',
        connected=False,
        orientation=(0, m.radians(-90), m.radians(5.5)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
    ),
    'palm.02.L': VirtualBone(
        head='left_hand_wrist',
        tail='left_hand_middle_finger_mcp',
        category='fingers',
        parent_bone='hand.L',
        connected=False,
        orientation=(0, m.radians(90), m.radians(-5.5)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
    ),
    'f_middle.01.R': VirtualBone(
        head='right_hand_middle_finger_mcp',
        tail='right_hand_middle_finger_pip',
        category='fingers',
        parent_bone='palm.02.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_min_x=-30,
        rot_limit_max_x=60,
        rot_limit_min_z=-30,
        rot_limit_max_z=30,
    ),
    'f_middle.01.L': VirtualBone(
        head='left_hand_middle_finger_mcp',
        tail='left_hand_middle_finger_pip',
        category='fingers',
        parent_bone='palm.02.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
        rot_limit_max_x=30,
        rot_limit_min_z=-30,
        rot_limit_max_z=30,
    ),
    'f_middle.02.R': VirtualBone(
        head='right_hand_middle_finger_pip',
        tail='right_hand_middle_finger_dip',
        category='fingers',
        parent_bone='f_middle.01.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=90,
    ),
    'f_middle.02.L': VirtualBone(
        head='left_hand_middle_finger_pip',
        tail='left_hand_middle_finger_dip',
        category='fingers',
        parent_bone='f_middle.01.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-90,
    ),
    'f_middle.03.R': VirtualBone(
        head='right_hand_middle_finger_dip',
        tail='right_hand_middle_finger_tip',
        category='fingers',
        parent_bone='f_middle.02.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=60,
    ),
    'f_middle.03.L': VirtualBone(
        head='left_hand_middle_finger_dip',
        tail='left_hand_middle_finger_tip',
        category='fingers',
        parent_bone='f_middle.02.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
    ),
    'palm.03.R': VirtualBone(
        head='right_hand_wrist',
        tail='right_hand_ring_finger_mcp',
        category='fingers',
        parent_bone='hand.R',
        connected=False,
        orientation=(0, m.radians(-90), m.radians(-7.3)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
        rot_limit_min_z=-16,
        rot_limit_max_z=-14,
    ),
    'palm.03.L': VirtualBone(
        head='left_hand_wrist',
        tail='left_hand_ring_finger_mcp',
        category='fingers',
        parent_bone='hand.L',
        connected=False,
        orientation=(0, m.radians(90), m.radians(7.3)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
        rot_limit_min_z=-16,
        rot_limit_max_z=-14,
    ),
    'f_ring.01.R': VirtualBone(
        head='right_hand_ring_finger_mcp',
        tail='right_hand_ring_finger_pip',
        category='fingers',
        parent_bone='palm.03.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_min_x=-30,
        rot_limit_max_x=60,
        rot_limit_min_z=-20,
        rot_limit_max_z=30,
    ),
    'f_ring.01.L': VirtualBone(
        head='left_hand_ring_finger_mcp',
        tail='left_hand_ring_finger_pip',
        category='fingers',
        parent_bone='palm.03.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
        rot_limit_max_x=30,
        rot_limit_min_z=-20,
        rot_limit_max_z=30,
    ),
    'f_ring.02.R': VirtualBone(
        head='right_hand_ring_finger_pip',
        tail='right_hand_ring_finger_dip',
        category='fingers',
        parent_bone='f_ring.01.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=90,
    ),
    'f_ring.02.L': VirtualBone(
        head='left_hand_ring_finger_pip',
        tail='left_hand_ring_finger_dip',
        category='fingers',
        parent_bone='f_ring.01.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-90,
    ),
    'f_ring.03.R': VirtualBone(
        head='right_hand_ring_finger_dip',
        tail='right_hand_ring_finger_tip',
        category='fingers',
        parent_bone='f_ring.02.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=60,
    ),
    'f_ring.03.L': VirtualBone(
        head='left_hand_ring_finger_dip',
        tail='left_hand_ring_finger_tip',
        category='fingers',
        parent_bone='f_ring.02.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
    ),
    'palm.04.R': VirtualBone(
        head='right_hand_wrist',
        tail='right_hand_pinky_mcp',
        category='fingers',
        parent_bone='hand.R',
        connected=False,
        orientation=(0, m.radians(-90), m.radians(-19)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
        rot_limit_min_z=-31,
        rot_limit_max_z=-29,
    ),
    'palm.04.L': VirtualBone(
        head='left_hand_wrist',
        tail='left_hand_pinky_mcp',
        category='fingers',
        parent_bone='hand.L',
        connected=False,
        orientation=(0, m.radians(90), m.radians(19)),
        parent_position='head',
        rot_limit_min_x=-180,
        rot_limit_max_x=180,
        rot_limit_min_z=-31,
        rot_limit_max_z=-29,
    ),
    'f_pinky.01.R': VirtualBone(
        head='right_hand_pinky_mcp',
        tail='right_hand_pinky_pip',
        category='fingers',
        parent_bone='palm.04.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_min_x=-30,
        rot_limit_max_x=60,
        rot_limit_min_z=-30,
        rot_limit_max_z=40,
    ),
    'f_pinky.01.L': VirtualBone(
        head='left_hand_pinky_mcp',
        tail='left_hand_pinky_pip',
        category='fingers',
        parent_bone='palm.04.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
        rot_limit_max_x=30,
        rot_limit_min_z=-30,
        rot_limit_max_z=40,
    ),
    'f_pinky.02.R': VirtualBone(
        head='right_hand_pinky_pip',
        tail='right_hand_pinky_dip',
        category='fingers',
        parent_bone='f_pinky.01.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=90,
    ),
    'f_pinky.02.L': VirtualBone(
        head='left_hand_pinky_pip',
        tail='left_hand_pinky_dip',
        category='fingers',
        parent_bone='f_pinky.01.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-90,
    ),
    'f_pinky.03.R': VirtualBone(
        head='right_hand_pinky_dip',
        tail='right_hand_pinky_tip',
        category='fingers',
        parent_bone='f_pinky.02.R',
        connected=True,
        orientation=(0, m.radians(-90), 0),
        parent_position='tail',
        rot_limit_max_x=60,
    ),
    'f_pinky.03.L': VirtualBone(
        head='left_hand_pinky_dip',
        tail='left_hand_pinky_tip',
        category='fingers',
        parent_bone='f_pinky.02.L',
        connected=True,
        orientation=(0, m.radians(90), 0),
        parent_position='tail',
        rot_limit_min_x=-60,
    ),
    'thigh.R': VirtualBone(
        head='right_hip',
        tail='right_knee',
        parent_bone='pelvis.R',
        connected=True,
        orientation=(0, m.radians(180), 0),
        parent_position='tail',
    ),
    'thigh.L': VirtualBone(
        head='left_hip',
        tail='left_knee',
        parent_bone='pelvis.L',
        connected=True,
        orientation=(0, m.radians(180), 0),
        parent_position='tail',
    ),
    'shin.R': VirtualBone(
        head='right_knee',
        tail='right_ankle',
        parent_bone='thigh.R',
        connected=True,
        orientation=(0, m.radians(180), 0),
        parent_position='tail',
    ),
    'shin.L': VirtualBone(
        head='left_knee',
        tail='left_ankle',
        parent_bone='thigh.L',
        connected=True,
        orientation=(0, m.radians(180), 0),
        parent_position='tail',
    ),
    'foot.R': VirtualBone(
        head='right_ankle',
        tail='right_foot_index',
        parent_bone='shin.R',
        connected=True,
        orientation=(0, m.radians(113), 0),
        parent_position='tail',
    ),
    'foot.L': VirtualBone(
        head='left_ankle',
        tail='left_foot_index',
        parent_bone='shin.L',
        connected=True,
        orientation=(0, m.radians(113), 0),
        parent_position='tail',
    ),
    'heel.02.R': VirtualBone(
        head='right_ankle',
        tail='right_heel',
        parent_bone='shin.R',
        connected=True,
        orientation=(m.radians(195), 0, 0),
        parent_position='tail',
    ), 
    'heel.02.L': VirtualBone(
        head='left_ankle',
        tail='left_heel',
        parent_bone='shin.L',
        connected=True,
        orientation=(m.radians(195), 0, 0),
        parent_position='tail',
    ),
}