"""
Dictionary with all the major bones with head and tail empties.
Also has variables to store each frame bone lengths, median and stdev amoong
others.
"""

virtual_bones = {
    'pelvis.R': {
        'head' : 'hips_center',
        'tail' : 'right_hip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'pelvis.L': {
        'head' : 'hips_center',
        'tail' : 'left_hip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'spine': {
        'head' : 'hips_center',
        'tail' : 'trunk_center',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'spine.001': {
        'head' : 'trunk_center',
        'tail' : 'neck_center',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'neck': {
        'head' : 'neck_center',
        'tail' : 'head_center',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'head_nose': { # Aux bone from head center to nose tip to align face bones 
        'head' : 'head_center',
        'tail' : 'nose',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'shoulder.R': {
        'head' : 'neck_center',
        'tail' : 'right_shoulder',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'shoulder.L': {
        'head' : 'neck_center',
        'tail' : 'left_shoulder',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'upper_arm.R': {
        'head' : 'right_shoulder',
        'tail' : 'right_elbow',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'upper_arm.L': {
        'head' : 'left_shoulder',
        'tail' : 'left_elbow',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'forearm.R': {
        'head' : 'right_elbow',
        'tail' : 'right_wrist',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'forearm.L': {
        'head' : 'left_elbow',
        'tail' : 'left_wrist',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'hand.R': {
        'head' : 'right_wrist',
        'tail' : 'right_hand_middle',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'hand.L': {
        'head' : 'left_wrist',
        'tail' : 'left_hand_middle',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.carpal.R': { # Auxiliary bone to align right_hand_thumb_cmc empty
        'head' : 'right_hand_wrist',
        'tail' : 'right_hand_thumb_cmc',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'hands',
        'parent_bone' : 'hand.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.carpal.L': { # Auxiliary bone to align the left_hand_thumb_cmc empty
        'head' : 'left_hand_wrist',
        'tail' : 'left_hand_thumb_cmc',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'hands',
        'parent_bone' : 'hand.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.01.R': {
        'head' : 'right_hand_thumb_cmc',
        'tail' : 'right_hand_thumb_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.carpal.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -50,
        'rot_limit_max_x' : 50,
        'rot_limit_min_z' : -60,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.01.L': {
        'head' : 'left_hand_thumb_cmc',
        'tail' : 'left_hand_thumb_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.carpal.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -50,
        'rot_limit_max_x' : 50,
        'rot_limit_min_z' : -60,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.02.R': {
        'head' : 'right_hand_thumb_mcp',
        'tail' : 'right_hand_thumb_ip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 40,
        'rot_limit_min_z' : -10,
        'rot_limit_max_z' : 10,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.02.L': {
        'head' : 'left_hand_thumb_mcp',
        'tail' : 'left_hand_thumb_ip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -40,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : -10,
        'rot_limit_max_z' : 10,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.03.R': {
        'head' : 'right_hand_thumb_ip',
        'tail' : 'right_hand_thumb_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -10,
        'rot_limit_max_x' : 90,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thumb.03.L': {
        'head' : 'left_hand_thumb_ip',
        'tail' : 'left_hand_thumb_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'thumb.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -90,
        'rot_limit_max_x' : 10,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.01.R': {
        'head' : 'right_hand_wrist',
        'tail' : 'right_hand_index_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -360,
        'rot_limit_max_x' : 360,
        'rot_limit_min_z' : 14,
        'rot_limit_max_z' : 16,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.01.L': {
        'head' : 'left_hand_wrist',
        'tail' : 'left_hand_index_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : 14,
        'rot_limit_max_z' : 16,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.01.R': {
        'head' : 'right_hand_index_finger_mcp',
        'tail' : 'right_hand_index_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -30,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 40,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.01.L': {
        'head' : 'left_hand_index_finger_mcp',
        'tail' : 'left_hand_index_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 30,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 40,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.02.R': {
        'head' : 'right_hand_index_finger_pip',
        'tail' : 'right_hand_index_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_index.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 90,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : True,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.02.L': {
        'head' : 'left_hand_index_finger_pip',
        'tail' : 'left_hand_index_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_index.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -90,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.03.R': {
        'head' : 'right_hand_index_finger_dip',
        'tail' : 'right_hand_index_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_index.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : True,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_index.03.L': {
        'head' : 'left_hand_index_finger_dip',
        'tail' : 'left_hand_index_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_index.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.02.R': {
        'head' : 'right_hand_wrist',
        'tail' : 'right_hand_middle_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.02.L': {
        'head' : 'left_hand_wrist',
        'tail' : 'left_hand_middle_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.01.R': {
        'head' : 'right_hand_middle_finger_mcp',
        'tail' : 'right_hand_middle_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -30,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.01.L': {
        'head' : 'left_hand_middle_finger_mcp',
        'tail' : 'left_hand_middle_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 30,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.02.R': {
        'head' : 'right_hand_middle_finger_pip',
        'tail' : 'right_hand_middle_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_middle.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 90,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.02.L': {
        'head' : 'left_hand_middle_finger_pip',
        'tail' : 'left_hand_middle_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_middle.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -90,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.03.R': {
        'head' : 'right_hand_middle_finger_dip',
        'tail' : 'right_hand_middle_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_middle.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_middle.03.L': {
        'head' : 'left_hand_middle_finger_dip',
        'tail' : 'left_hand_middle_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_middle.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.03.R': {
        'head' : 'right_hand_wrist',
        'tail' : 'right_hand_ring_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : -16,
        'rot_limit_max_z' : -14,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.03.L': {
        'head' : 'left_hand_wrist',
        'tail' : 'left_hand_ring_finger_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : -16,
        'rot_limit_max_z' : -14,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.01.R': {
        'head' : 'right_hand_ring_finger_mcp',
        'tail' : 'right_hand_ring_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.03.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -30,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : -20,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.01.L': {
        'head' : 'left_hand_ring_finger_mcp',
        'tail' : 'left_hand_ring_finger_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.03.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 30,
        'rot_limit_min_z' : -20,
        'rot_limit_max_z' : 30,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.02.R': {
        'head' : 'right_hand_ring_finger_pip',
        'tail' : 'right_hand_ring_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_ring.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 90,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.02.L': {
        'head' : 'left_hand_ring_finger_pip',
        'tail' : 'left_hand_ring_finger_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_ring.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -90,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.03.R': {
        'head' : 'right_hand_ring_finger_dip',
        'tail' : 'right_hand_ring_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_ring.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_ring.03.L': {
        'head' : 'left_hand_ring_finger_dip',
        'tail' : 'left_hand_ring_finger_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_ring.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.04.R': {
        'head' : 'right_hand_wrist',
        'tail' : 'right_hand_pinky_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : -31,
        'rot_limit_max_z' : -29,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'palm.04.L': {
        'head' : 'left_hand_wrist',
        'tail' : 'left_hand_pinky_mcp',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'hand.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -180,
        'rot_limit_max_x' : 180,
        'rot_limit_min_z' : -31,
        'rot_limit_max_z' : -29,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.01.R': {
        'head' : 'right_hand_pinky_mcp',
        'tail' : 'right_hand_pinky_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.04.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -30,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 40,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.01.L': {
        'head' : 'left_hand_pinky_mcp',
        'tail' : 'left_hand_pinky_pip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'palm.04.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 30,
        'rot_limit_min_z' : -30,
        'rot_limit_max_z' : 40,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.02.R': {
        'head' : 'right_hand_pinky_pip',
        'tail' : 'right_hand_pinky_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_pinky.01.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 90,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.02.L': {
        'head' : 'left_hand_pinky_pip',
        'tail' : 'left_hand_pinky_dip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_pinky.01.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -90,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.03.R': {
        'head' : 'right_hand_pinky_dip',
        'tail' : 'right_hand_pinky_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_pinky.02.R',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 60,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'f_pinky.03.L': {
        'head' : 'left_hand_pinky_dip',
        'tail' : 'left_hand_pinky_tip',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : 'fingers',
        'parent_bone' : 'f_pinky.02.L',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : -60,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thigh.R': {
        'head' : 'right_hip',
        'tail' : 'right_knee',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'thigh.L': {
        'head' : 'left_hip',
        'tail' : 'left_knee',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'shin.R': {
        'head' : 'right_knee',
        'tail' : 'right_ankle',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'shin.L': {
        'head' : 'left_knee',
        'tail' : 'left_ankle',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'foot.R': {
        'head' : 'right_ankle',
        'tail' : 'right_foot_index',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'foot.L': {
        'head' : 'left_ankle',
        'tail' : 'left_foot_index',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'heel.02.R': {
        'head' : 'right_ankle',
        'tail' : 'right_heel',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
    'heel.02.L': {
        'head' : 'left_ankle',
        'tail' : 'left_heel',
        'lengths' : [],
        'median' : 0,
        'stdev' : 0,
        'category' : '',
        'parent_bone' : '',
        'bone_x_axis' : (0,0,0),
        'bone_y_axis' : (0,0,0),
        'bone_z_axis' : (0,0,0),
        'rot_limit_min_x' : 0,
        'rot_limit_max_x' : 0,
        'rot_limit_min_z' : 0,
        'rot_limit_max_z' : 0,
        'has_skelly_part' : False,
        'default_origin' : (0, 0, 0),
        'default_length' : 0,},
}
