# Dictionary with the Anthropomorphic human dimensions by Winter, D. This values will be used the specified actor height when using standard bone lengths
anthropomorphic_dimensions = {
    'pelvis.R': {
        'dimension': 0.0955},
    'pelvis.L': {
        'dimension': 0.0955},
    'spine': {
        'dimension': 0.144},
    'spine.001': {
        'dimension': 0.144},
    'neck': {
        'dimension': 0.118},
    'head_nose': { # Auxiliary bone from head center to nose tip to align the face bones 
        'dimension': 0.0743},
    'shoulder.R': {
        'dimension': 0.129},
    'shoulder.L': {
        'dimension': 0.129},
    'upper_arm.R': {
        'dimension': 0.186},
    'upper_arm.L': {
        'dimension': 0.186},
    'forearm.R': {
        'dimension': 0.146},
    'forearm.L': {
        'dimension': 0.146},
    'hand.R': {
        'dimension': 0.054},
    'hand.L': {
        'dimension': 0.054},
    'thumb.carpal.R': { # Auxiliary bone to align the right_hand_thumb_cmc empty
        'dimension': 0.03},
    'thumb.carpal.L': { # Auxiliary bone to align the left_hand_thumb_cmc empty
        'dimension': 0.03},
    'thumb.01.R': {
        'dimension': 0.021},
    'thumb.01.L': {
        'dimension': 0.021},
    'thumb.02.R': {
        'dimension': 0.024},
    'thumb.02.L': {
        'dimension': 0.024},
    'thumb.03.R': {
        'dimension': 0.0192},
    'thumb.03.L': {
        'dimension': 0.0192},
    'palm.01.R': {
        'dimension': 0.054},
    'palm.01.L': {
        'dimension': 0.054},
    'f_index.01.R': {
        'dimension': 0.0282},
    'f_index.01.L': {
        'dimension': 0.0282},
    'f_index.02.R': {
        'dimension': 0.0186},
    'f_index.02.L': {
        'dimension': 0.0186},
    'f_index.03.R': {
        'dimension': 0.015},
    'f_index.03.L': {
        'dimension': 0.015},
    'palm.02.R': {
        'dimension': 0.054},
    'palm.02.L': {
        'dimension': 0.054},
    'f_middle.01.R': {
        'dimension': 0.03},
    'f_middle.01.L': {
        'dimension': 0.03},
    'f_middle.02.R': {
        'dimension': 0.0192},
    'f_middle.02.L': {
        'dimension': 0.0192},
    'f_middle.03.R': {
        'dimension': 0.0156},
    'f_middle.03.L': {
        'dimension': 0.0156},
    'palm.03.R': {
        'dimension': 0.0522},
    'palm.03.L': {
        'dimension': 0.0522},
    'f_ring.01.R': {
        'dimension': 0.0282},
    'f_ring.01.L': {
        'dimension': 0.0282},
    'f_ring.02.R': {
        'dimension': 0.0186},
    'f_ring.02.L': {
        'dimension': 0.0186},
    'f_ring.03.R': {
        'dimension': 0.0156},
    'f_ring.03.L': {
        'dimension': 0.0156},
    'palm.04.R': {
        'dimension': 0.0498},
    'palm.04.L': {
        'dimension': 0.0498},
    'f_pinky.01.R': {
        'dimension': 0.0264},
    'f_pinky.01.L': {
        'dimension': 0.0264},
    'f_pinky.02.R': {
        'dimension': 0.0156},
    'f_pinky.02.L': {
        'dimension': 0.0156},
    'f_pinky.03.R': {
        'dimension': 0.0144},
    'f_pinky.03.L': {
        'dimension': 0.0144},
    'thigh.R': {
        'dimension': 0.245},
    'thigh.L': {
        'dimension': 0.245},
    'shin.R': {
        'dimension': 0.246},
    'shin.L': {
        'dimension': 0.246},
    'foot.R': {
        'dimension': 0.152},
    'foot.L': {
        'dimension': 0.152},
    'heel.02.R': {
        'dimension': 0.039},
    'heel.02.L': {
        'dimension': 0.039},
}

# Create a dictionary with all the major bones with their head and tail empties.
# Also add variables to store each frame bone lengths, the median and the stdev.
virtual_bones = {
    'pelvis.R': {
        'head'              : 'hips_center',
        'tail'              : 'right_hip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'pelvis.L': {
        'head'              : 'hips_center',
        'tail'              : 'left_hip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'spine': {
        'head'              : 'hips_center',
        'tail'              : 'trunk_center',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'spine.001': {
        'head'              : 'trunk_center',
        'tail'              : 'neck_center',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'neck': {
        'head'              : 'neck_center',
        'tail'              : 'head_center',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'head_nose': { # Auxiliary bone from head center to nose tip to align the face bones 
        'head'              : 'head_center',
        'tail'              : 'nose',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'shoulder.R': {
        'head'              : 'neck_center',
        'tail'              : 'right_shoulder',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'shoulder.L': {
        'head'              : 'neck_center',
        'tail'              : 'left_shoulder',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'upper_arm.R': {
        'head'              : 'right_shoulder',
        'tail'              : 'right_elbow',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'upper_arm.L': {
        'head'              : 'left_shoulder',
        'tail'              : 'left_elbow',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'forearm.R': {
        'head'              : 'right_elbow',
        'tail'              : 'right_wrist',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'forearm.L': {
        'head'              : 'left_elbow',
        'tail'              : 'left_wrist',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'hand.R': {
        'head'              : 'right_wrist',
        'tail'              : 'right_hand_middle',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'hand.L': {
        'head'              : 'left_wrist',
        'tail'              : 'left_hand_middle',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.carpal.R': { # Auxiliary bone to align the right_hand_thumb_cmc empty
        'head'              : 'right_hand_wrist',
        'tail'              : 'right_hand_thumb_cmc',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'hands',
        'parent_bone'       : 'hand.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.carpal.L': { # Auxiliary bone to align the left_hand_thumb_cmc empty
        'head'              : 'left_hand_wrist',
        'tail'              : 'left_hand_thumb_cmc',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'hands',
        'parent_bone'       : 'hand.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.01.R': {
        'head'              : 'right_hand_thumb_cmc',
        'tail'              : 'right_hand_thumb_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.carpal.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -50,
        'rot_limit_max_x'   : 50,
        'rot_limit_min_z'   : -60,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.01.L': {
        'head'              : 'left_hand_thumb_cmc',
        'tail'              : 'left_hand_thumb_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.carpal.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -50,
        'rot_limit_max_x'   : 50,
        'rot_limit_min_z'   : -60,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.02.R': {
        'head'              : 'right_hand_thumb_mcp',
        'tail'              : 'right_hand_thumb_ip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 40,
        'rot_limit_min_z'   : -10,
        'rot_limit_max_z'   : 10,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.02.L': {
        'head'              : 'left_hand_thumb_mcp',
        'tail'              : 'left_hand_thumb_ip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -40,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : -10,
        'rot_limit_max_z'   : 10,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.03.R': {
        'head'              : 'right_hand_thumb_ip',
        'tail'              : 'right_hand_thumb_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -10,
        'rot_limit_max_x'   : 90,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thumb.03.L': {
        'head'              : 'left_hand_thumb_ip',
        'tail'              : 'left_hand_thumb_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'thumb.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -90,
        'rot_limit_max_x'   : 10,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.01.R': {
        'head'              : 'right_hand_wrist',
        'tail'              : 'right_hand_index_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -360,
        'rot_limit_max_x'   : 360,
        'rot_limit_min_z'   : 14,
        'rot_limit_max_z'   : 16,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.01.L': {
        'head'              : 'left_hand_wrist',
        'tail'              : 'left_hand_index_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : 14,
        'rot_limit_max_z'   : 16,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.01.R': {
        'head'              : 'right_hand_index_finger_mcp',
        'tail'              : 'right_hand_index_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -30,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 40,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.01.L': {
        'head'              : 'left_hand_index_finger_mcp',
        'tail'              : 'left_hand_index_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 30,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 40,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.02.R': {
        'head'              : 'right_hand_index_finger_pip',
        'tail'              : 'right_hand_index_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_index.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 90,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : True,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.02.L': {
        'head'              : 'left_hand_index_finger_pip',
        'tail'              : 'left_hand_index_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_index.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -90,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.03.R': {
        'head'              : 'right_hand_index_finger_dip',
        'tail'              : 'right_hand_index_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_index.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : True,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_index.03.L': {
        'head'              : 'left_hand_index_finger_dip',
        'tail'              : 'left_hand_index_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_index.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.02.R': {
        'head'              : 'right_hand_wrist',
        'tail'              : 'right_hand_middle_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.02.L': {
        'head'              : 'left_hand_wrist',
        'tail'              : 'left_hand_middle_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.01.R': {
        'head'              : 'right_hand_middle_finger_mcp',
        'tail'              : 'right_hand_middle_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -30,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.01.L': {
        'head'              : 'left_hand_middle_finger_mcp',
        'tail'              : 'left_hand_middle_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 30,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.02.R': {
        'head'              : 'right_hand_middle_finger_pip',
        'tail'              : 'right_hand_middle_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_middle.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 90,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.02.L': {
        'head'              : 'left_hand_middle_finger_pip',
        'tail'              : 'left_hand_middle_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_middle.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -90,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.03.R': {
        'head'              : 'right_hand_middle_finger_dip',
        'tail'              : 'right_hand_middle_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_middle.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_middle.03.L': {
        'head'              : 'left_hand_middle_finger_dip',
        'tail'              : 'left_hand_middle_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_middle.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.03.R': {
        'head'              : 'right_hand_wrist',
        'tail'              : 'right_hand_ring_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : -16,
        'rot_limit_max_z'   : -14,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.03.L': {
        'head'              : 'left_hand_wrist',
        'tail'              : 'left_hand_ring_finger_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : -16,
        'rot_limit_max_z'   : -14,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.01.R': {
        'head'              : 'right_hand_ring_finger_mcp',
        'tail'              : 'right_hand_ring_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.03.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -30,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : -20,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.01.L': {
        'head'              : 'left_hand_ring_finger_mcp',
        'tail'              : 'left_hand_ring_finger_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.03.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 30,
        'rot_limit_min_z'   : -20,
        'rot_limit_max_z'   : 30,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.02.R': {
        'head'              : 'right_hand_ring_finger_pip',
        'tail'              : 'right_hand_ring_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_ring.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 90,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.02.L': {
        'head'              : 'left_hand_ring_finger_pip',
        'tail'              : 'left_hand_ring_finger_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_ring.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -90,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.03.R': {
        'head'              : 'right_hand_ring_finger_dip',
        'tail'              : 'right_hand_ring_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_ring.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_ring.03.L': {
        'head'              : 'left_hand_ring_finger_dip',
        'tail'              : 'left_hand_ring_finger_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_ring.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.04.R': {
        'head'              : 'right_hand_wrist',
        'tail'              : 'right_hand_pinky_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : -31,
        'rot_limit_max_z'   : -29,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'palm.04.L': {
        'head'              : 'left_hand_wrist',
        'tail'              : 'left_hand_pinky_mcp',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'hand.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -180,
        'rot_limit_max_x'   : 180,
        'rot_limit_min_z'   : -31,
        'rot_limit_max_z'   : -29,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.01.R': {
        'head'              : 'right_hand_pinky_mcp',
        'tail'              : 'right_hand_pinky_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.04.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -30,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 40,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.01.L': {
        'head'              : 'left_hand_pinky_mcp',
        'tail'              : 'left_hand_pinky_pip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'palm.04.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 30,
        'rot_limit_min_z'   : -30,
        'rot_limit_max_z'   : 40,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.02.R': {
        'head'              : 'right_hand_pinky_pip',
        'tail'              : 'right_hand_pinky_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_pinky.01.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 90,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.02.L': {
        'head'              : 'left_hand_pinky_pip',
        'tail'              : 'left_hand_pinky_dip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_pinky.01.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -90,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.03.R': {
        'head'              : 'right_hand_pinky_dip',
        'tail'              : 'right_hand_pinky_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_pinky.02.R',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 60,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'f_pinky.03.L': {
        'head'              : 'left_hand_pinky_dip',
        'tail'              : 'left_hand_pinky_tip',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : 'fingers',
        'parent_bone'       : 'f_pinky.02.L',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : -60,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thigh.R': {
        'head'              : 'right_hip',
        'tail'              : 'right_knee',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'thigh.L': {
        'head'              : 'left_hip',
        'tail'              : 'left_knee',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'shin.R': {
        'head'              : 'right_knee',
        'tail'              : 'right_ankle',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'shin.L': {
        'head'              : 'left_knee',
        'tail'              : 'left_ankle',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'foot.R': {
        'head'              : 'right_ankle',
        'tail'              : 'right_foot_index',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'foot.L': {
        'head'              : 'left_ankle',
        'tail'              : 'left_foot_index',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'heel.02.R': {
        'head'              : 'right_ankle',
        'tail'              : 'right_heel',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
    'heel.02.L': {
        'head'              : 'left_ankle',
        'tail'              : 'left_heel',
        'lengths'           : [],
        'median'            : 0,
        'stdev'             : 0,
        'category'          : '',
        'parent_bone'       : '',
        'bone_x_axis'       : (0,0,0),
        'bone_y_axis'       : (0,0,0),
        'bone_z_axis'       : (0,0,0),
        'rot_limit_min_x'   : 0,
        'rot_limit_max_x'   : 0,
        'rot_limit_min_z'   : 0,
        'rot_limit_max_z'   : 0,
        'has_skelly_part'   : False,
        'default_origin'    : (0, 0, 0),
        'default_length'    : 0,},
}

# Dictionary containing the empty children for each of the capture empties.
# This will be used to correct the position of the empties (and its children) that are outside the bone length interval defined by x*stdev
empties_dict = {
    'hips_center': {
        'children'      : ['right_hip', 'left_hip', 'trunk_center'],
        'category'      : 'core',
        'tail_of_bone'  : ''},
    'trunk_center': {
        'children'      : ['neck_center'],
        'category'      : 'core',
        'tail_of_bone'  : 'spine'},
    'neck_center': {
        'children'      : ['right_shoulder', 'left_shoulder', 'head_center'],
        'category'      : 'core',
        'tail_of_bone'  : 'spine.001'},
    'head_center': {
        'children'      : ['nose', 'mouth_right', 'mouth_left', 'right_eye', 'right_eye_inner', 'right_eye_outer', 'left_eye', 'left_eye_inner', 'left_eye_outer', 'right_ear', 'left_ear'],
        'category'      : 'core',
        'tail_of_bone'  : 'neck'},
    'right_shoulder': {
        'children'      : ['right_elbow'],
        'category'      : 'arms',
        'tail_of_bone'  : 'shoulder.R'},
    'left_shoulder': {
        'children'      : ['left_elbow'],
        'category'      : 'arms',
        'tail_of_bone'  : 'shoulder.L'},
    'right_elbow': {
        'children'      : ['right_wrist'],
        'category'      : 'arms',
        'tail_of_bone'  : 'upper_arm.R'},
    'left_elbow': {
        'children'      : ['left_wrist'],
        'category'      : 'arms',
        'tail_of_bone'  : 'upper_arm.L'},
    'right_wrist': {
        'children'      : ['right_thumb', 'right_index', 'right_pinky', 'right_hand', 'right_hand_middle', 'right_hand_wrist'],
        'category'      : 'hands',
        'tail_of_bone'  : 'forearm.R'},
    'left_wrist': {
        'children'      : ['left_thumb', 'left_index', 'left_pinky', 'left_hand', 'left_hand_middle', 'left_hand_wrist'],
        'category'      : 'hands',
        'tail_of_bone'  : 'forearm.L'},
    'right_hand_middle': {
        'children'      : [],
        'category'      : 'hands',
        'tail_of_bone'  : 'hand.R'},
    'left_hand_middle': {
        'children'      : [],
        'category'      : 'hands',
        'tail_of_bone'  : 'hand.L'},
    'right_hand_wrist': {
        'children'      : ['right_hand_thumb_cmc', 'right_hand_index_finger_mcp', 'right_hand_middle_finger_mcp', 'right_hand_ring_finger_mcp', 'right_hand_pinky_mcp'],
        'category'      : 'hands',
        'tail_of_bone'  : ''},
    'left_hand_wrist': {
        'children'      : ['left_hand_thumb_cmc', 'left_hand_index_finger_mcp', 'left_hand_middle_finger_mcp', 'left_hand_ring_finger_mcp', 'left_hand_pinky_mcp'],
        'category'      : 'hands',
        'tail_of_bone'  : ''},
    'right_hand_thumb_cmc': {
        'children'      : ['right_hand_thumb_mcp'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.carpal.R'},
    'left_hand_thumb_cmc': {
        'children'      : ['left_hand_thumb_mcp'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.carpal.L'},
    'right_hand_thumb_mcp': {
        'children'      : ['right_hand_thumb_ip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.01.R'},
    'left_hand_thumb_mcp': {
        'children'      : ['left_hand_thumb_ip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.01.L'},
    'right_hand_thumb_ip': {
        'children'      : ['right_hand_thumb_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.02.R'},
    'left_hand_thumb_ip': {
        'children'      : ['left_hand_thumb_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.02.L'},
    'right_hand_thumb_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.03.R'},
    'left_hand_thumb_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'thumb.03.L'},
    'right_hand_index_finger_mcp': {
        'children'      : ['right_hand_index_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.01.R'},
    'left_hand_index_finger_mcp': {
        'children'      : ['left_hand_index_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.01.L'},
    'right_hand_index_finger_pip': {
        'children'      : ['right_hand_index_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.01.R'},
    'left_hand_index_finger_pip': {
        'children'      : ['left_hand_index_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.01.L'},
    'right_hand_index_finger_dip': {
        'children'      : ['right_hand_index_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.02.R'},
    'left_hand_index_finger_dip': {
        'children'      : ['left_hand_index_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.02.L'},
    'right_hand_index_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.03.R'},
    'left_hand_index_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_index.03.L'},
    'right_hand_middle_finger_mcp': {
        'children'      : ['right_hand_middle_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.02.R'},
    'left_hand_middle_finger_mcp': {
        'children'      : ['left_hand_middle_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.02.L'},
    'right_hand_middle_finger_pip': {
        'children'      : ['right_hand_middle_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.01.R'},
    'left_hand_middle_finger_pip': {
        'children'      : ['left_hand_middle_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.01.L'},
    'right_hand_middle_finger_dip': {
        'children'      : ['right_hand_middle_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.02.R'},
    'left_hand_middle_finger_dip': {
        'children'      : ['left_hand_middle_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.02.L'},
    'right_hand_middle_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.03.R'},
    'left_hand_middle_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_middle.03.L'},
    'right_hand_ring_finger_mcp': {
        'children'      : ['right_hand_ring_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.03.R'},
    'left_hand_ring_finger_mcp': {
        'children'      : ['left_hand_ring_finger_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.03.L'},
    'right_hand_ring_finger_pip': {
        'children'      : ['right_hand_ring_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.01.R'},
    'left_hand_ring_finger_pip': {
        'children'      : ['left_hand_ring_finger_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.01.L'},
    'right_hand_ring_finger_dip': {
        'children'      : ['right_hand_ring_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.02.R'},
    'left_hand_ring_finger_dip': {
        'children'      : ['left_hand_ring_finger_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.02.L'},
    'right_hand_ring_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.03.R'},
    'left_hand_ring_finger_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_ring.03.L'},
    'right_hand_pinky_mcp': {
        'children'      : ['right_hand_pinky_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.04.R'},
    'left_hand_pinky_mcp': {
        'children'      : ['left_hand_pinky_pip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'palm.04.L'},
    'right_hand_pinky_pip': {
        'children'      : ['right_hand_pinky_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.01.R'},
    'left_hand_pinky_pip': {
        'children'      : ['left_hand_pinky_dip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.01.L'},
    'right_hand_pinky_dip': {
        'children'      : ['right_hand_pinky_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.02.R'},
    'left_hand_pinky_dip': {
        'children'      : ['left_hand_pinky_tip'],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.02.L'},
    'right_hand_pinky_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.03.R'},
    'left_hand_pinky_tip': {
        'children'      : [],
        'category'      : 'fingers',
        'tail_of_bone'  : 'f_pinky.03.L'},
    'right_hip': {
        'children'      : ['right_knee'],
        'category'      : 'legs',
        'tail_of_bone'  : 'pelvis.R'},
    'left_hip': {
        'children'      : ['left_knee'],
        'category'      : 'legs',
        'tail_of_bone'  : 'pelvis.L'},
    'right_knee': {
        'children'      : ['right_ankle'],
        'category'      : 'legs',
        'tail_of_bone'  : 'thigh.R'},
    'left_knee': {
        'children'      : ['left_ankle'],
        'category'      : 'legs',
        'tail_of_bone'  : 'thigh.L'},
    'right_ankle': {
        'children'      : ['right_foot_index', 'right_heel'],
        'category'      : 'feet',
        'tail_of_bone'  : 'shin.R'},
    'left_ankle': {
        'children'      : ['left_foot_index', 'left_heel'],
        'category'      : 'feet',
        'tail_of_bone'  : 'shin.L'},
    'right_heel': {
        'children'      : [],
        'category'      : 'feet',
        'tail_of_bone'  : 'heel.02.R'},
    'left_heel': {
        'children'      : [],
        'category'      : 'feet',
        'tail_of_bone'  : 'heel.02.L'},
    'right_foot_index': {
        'children'      : [],
        'category'      : 'feet',
        'tail_of_bone'  : 'foot.R'},
    'left_foot_index': {
        'children'      : [],
        'category'      : 'feet',
        'tail_of_bone'  : 'foot.L'},
}

# Dictionary of the bones ik constraints parameters
ik_constraint_parameters = {
    'forearm.R': {
        'base_bone_name': 'upper_arm.R',
        'pole_target_bone_name': 'arm_pole_target.R',
        'base_empty_marker_name': 'right_shoulder',
        'pole_target_empty_marker_name': 'right_elbow',
        'ik_empty_marker_name': 'right_wrist'},
    'forearm.L': {
        'base_bone_name': 'upper_arm.L',
        'pole_target_bone_name': 'arm_pole_target.L',
        'base_empty_marker_name': 'left_shoulder',
        'pole_target_empty_marker_name': 'left_elbow',
        'ik_empty_marker_name': 'left_wrist'},
    'shin.R': {
        'base_bone_name': 'thigh.R',
        'pole_target_bone_name': 'leg_pole_target.R',
        'base_empty_marker_name': 'right_hip',
        'pole_target_empty_marker_name': 'right_knee',
        'ik_empty_marker_name': 'right_ankle'},
    'shin.L': {
        'base_bone_name': 'thigh.L',
        'pole_target_bone_name': 'leg_pole_target.L',
        'base_empty_marker_name': 'left_hip',
        'pole_target_empty_marker_name': 'left_knee',
        'ik_empty_marker_name': 'left_ankle'},
}

# Dictionary of the pole bones parameters
ik_pole_bones = {
    'arm_pole_target.R': {
        'base_marker':      'right_shoulder',
        'pole_marker':      'right_elbow',
        'target_marker':    'right_wrist',
        'aux_markers': ['right_wrist', 'right_hand_thumb_cmc']},
    'arm_pole_target.L': {
        'base_marker':      'left_shoulder',
        'pole_marker':      'left_elbow',
        'target_marker':    'left_wrist',
        'aux_markers': ['left_wrist', 'left_hand_thumb_cmc']},
    'leg_pole_target.R': {
        'base_marker':      'right_hip',
        'pole_marker':      'right_knee',
        'target_marker':    'right_ankle',
        'aux_markers': ['right_ankle', 'right_heel']},
    'leg_pole_target.L': {
        'base_marker':          'left_hip',
        'pole_marker':          'left_knee',
        'target_marker':        'left_ankle',
        'aux_markers': ['left_ankle', 'left_heel']},
}

# Dictionary with all the Skelly mesh parts
skelly_parts = {
    'head': {
        'bones'                 : ['face'],         # List of bones represented by the mesh
        'bones_origin'          : (0, 0, 0),        # Origin of the bones
        'bones_end'             : (0, 0, 0),        # End of the bones
        'bones_length'          : 0,                # Total length of the bones
        'mesh_length'           : 0.044658516812,   # Length of the mesh
        # 'mesh_length'           : 0.014658516812, # Big Head Skelly
        'position_offset'       : (0, 0.03, 0.03),  # Position offset of the mesh as units of the bones length
        # 'position_offset'       : (0, 0.03, 0.23), # Big Head Skelly
        'adjust_rotation'       : False,            # Adjust the rotation of the mesh after applying the position offset
    },
    'spine': {
        'bones'                 : ['spine', 'spine.001', 'neck'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.70856,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'upper_arm.R': {
        'bones'                 : ['upper_arm.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.325418,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'upper_arm.L': {
        'bones'                 : ['upper_arm.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.325418,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'forearm.R': {
        'bones'                 : ['forearm.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.255504,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'forearm.L': {
        'bones'                 : ['forearm.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.255504,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'hand.R': {
        'bones'                 : ['hand.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.0845,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'hand.L': {
        'bones'                 : ['hand.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.0845,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.01.R': {
        'bones'                 : ['thumb.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03675,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.01.L': {
        'bones'                 : ['thumb.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03675,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.02.R': {
        'bones'                 : ['thumb.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.032224,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.02.L': {
        'bones'                 : ['thumb.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.032224,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.03.R': {
        'bones'                 : ['thumb.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.023374,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.03.L': {
        'bones'                 : ['thumb.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.023374,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'palm.01.R': {
        'bones'                 : ['palm.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085891,
        'position_offset'       : (-0.02, -0.025, 0),
        'adjust_rotation'       : True,
    },
    'palm.01.L': {
        'bones'                 : ['palm.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085891,
        'position_offset'       : (0.02, -0.025, 0),
        'adjust_rotation'       : True,
    },
    'palm.02.R': {
        'bones'                 : ['palm.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085828,
        'position_offset'       : (-0.02, -0.005, 0),
        'adjust_rotation'       : True,
    },
    'palm.02.L': {
        'bones'                 : ['palm.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085828,
        'position_offset'       : (0.02, -0.005, 0),
        'adjust_rotation'       : True,
    },
    'palm.03.R': {
        'bones'                 : ['palm.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.082869,
        'position_offset'       : (-0.02, 0.01, 0),
        'adjust_rotation'       : True,
    },
    'palm.03.L': {
        'bones'                 : ['palm.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.082869,
        'position_offset'       : (0.02, 0.01, 0),
        'adjust_rotation'       : True,
    },
    'palm.04.R': {
        'bones'                 : ['palm.04.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.070385,
        'position_offset'       : (-0.02, 0.025, 0),
        'adjust_rotation'       : True,
    },
    'palm.04.L': {
        'bones'                 : ['palm.04.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.070385,
        'position_offset'       : (0.02, 0.025, 0),
        'adjust_rotation'       : True,
    },
    'f_index.01.R': {
        'bones'                 : ['f_index.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053961,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.01.L': {
        'bones'                 : ['f_index.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053961,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.02.R': {
        'bones'                 : ['f_index.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.033378,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.02.L': {
        'bones'                 : ['f_index.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.033378,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.03.R': {
        'bones'                 : ['f_index.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024385,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.03.L': {
        'bones'                 : ['f_index.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024385,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.01.R': {
        'bones'                 : ['f_middle.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053792,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.01.L': {
        'bones'                 : ['f_middle.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053792,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.02.R': {
        'bones'                 : ['f_middle.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03347,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.02.L': {
        'bones'                 : ['f_middle.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03347,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.03.R': {
        'bones'                 : ['f_middle.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.028028,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.03.L': {
        'bones'                 : ['f_middle.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.028028,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.01.R': {
        'bones'                 : ['f_ring.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.046598,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.01.L': {
        'bones'                 : ['f_ring.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.046598,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.02.R': {
        'bones'                 : ['f_ring.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.036003,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.02.L': {
        'bones'                 : ['f_ring.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.036003,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.03.R': {
        'bones'                 : ['f_ring.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024413,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.03.L': {
        'bones'                 : ['f_ring.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024413,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.01.R': {
        'bones'                 : ['f_pinky.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.039485,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.01.L': {
        'bones'                 : ['f_pinky.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.039485,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.02.R': {
        'bones'                 : ['f_pinky.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.027034,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.02.L': {
        'bones'                 : ['f_pinky.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.027034,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.03.R': {
        'bones'                 : ['f_pinky.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.020288,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.03.L': {
        'bones'                 : ['f_pinky.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.020288,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thigh.R': {
        'bones'                 : ['thigh.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.42875,
        'position_offset'       : (0, -0.04, 0),
        'adjust_rotation'       : False,
    },
    'thigh.L': {
        'bones'                 : ['thigh.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.42875,
        'position_offset'       : (0, -0.04, 0),
        'adjust_rotation'       : False,
    },
    'shin.R': {
        'bones'                 : ['shin.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.412281,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'shin.L': {
        'bones'                 : ['shin.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.412281,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'foot.R': {
        'bones'                 : ['foot.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.226,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'foot.L': {
        'bones'                 : ['foot.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.226,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'heel.02.R': {
        'bones'                 : ['heel.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.150255,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'heel.02.L': {
        'bones'                 : ['heel.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.150255,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
}

foot_locking_markers = {
    'left_foot': {
        'base': ['left_foot_index', 'left_heel'],
        'ankle': ['left_ankle'],
        'bones': ['foot.L', 'heel.02.L'],
        'compensation_markers': ['left_knee', 'left_hip']
    },
    'right_foot': {
        'base': ['right_foot_index', 'right_heel'],
        'ankle': ['right_ankle'],
        'bones': ['foot.R', 'heel.02.R'],
        'compensation_markers': ['right_knee', 'right_hip']
    }
}