"""
Dictionary with all the Skelly mesh parts. It is used when adding the
Skelly mesh to the rig. Each bone has an individual mesh.
"""

SKELLY_BONES = {
    'head': {
        'bones' : ['face'], # Bones of the mesh
        'bones_origin' : (0, 0, 0), # Origin of the bones
        'bones_end' : (0, 0, 0), # End of the bones
        'bones_length' : 0, # Total length of the bones
        'mesh_length' : 0.244915, # Length of the mesh
        # 'mesh_length' : 0.014658516812, # Big Head Skelly
        'position_offset' : (0, 0, 0.03), # Position offset of the mesh
        # 'position_offset' : (0, 0.03, 0.23), # Big Head Skelly
        'adjust_rotation' : False, # Adjust rotation of mesh after offset
    },
    'spine': {
        'bones'                 : ['spine', 'spine.001', 'neck'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.70856,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'upper_arm.R': {
        'bones'                 : ['upper_arm.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.325418,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'upper_arm.L': {
        'bones'                 : ['upper_arm.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.325418,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'forearm.R': {
        'bones'                 : ['forearm.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.255504,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'forearm.L': {
        'bones'                 : ['forearm.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.255504,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'hand.R': {
        'bones'                 : ['hand.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.0845,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'hand.L': {
        'bones'                 : ['hand.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.0845,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.01.R': {
        'bones'                 : ['thumb.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03675,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.01.L': {
        'bones'                 : ['thumb.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03675,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.02.R': {
        'bones'                 : ['thumb.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.032224,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.02.L': {
        'bones'                 : ['thumb.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.032224,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.03.R': {
        'bones'                 : ['thumb.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.023374,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thumb.03.L': {
        'bones'                 : ['thumb.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.023374,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'palm.01.R': {
        'bones'                 : ['palm.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085891,
        'position_offset'       : (0, -0.025, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.01.L': {
        'bones'                 : ['palm.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085891,
        'position_offset'       : (0, -0.025, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.02.R': {
        'bones'                 : ['palm.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085828,
        'position_offset'       : (0, -0.005, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.02.L': {
        'bones'                 : ['palm.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.085828,
        'position_offset'       : (0, -0.005, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.03.R': {
        'bones'                 : ['palm.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.082869,
        'position_offset'       : (0, 0.01, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.03.L': {
        'bones'                 : ['palm.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.082869,
        'position_offset'       : (0, 0.01, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.04.R': {
        'bones'                 : ['palm.04.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.070385,
        'position_offset'       : (0, 0.025, 0.02),
        'adjust_rotation'       : True,
    },
    'palm.04.L': {
        'bones'                 : ['palm.04.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.070385,
        'position_offset'       : (0, 0.025, 0.02),
        'adjust_rotation'       : True,
    },
    'f_index.01.R': {
        'bones'                 : ['f_index.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053961,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.01.L': {
        'bones'                 : ['f_index.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053961,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.02.R': {
        'bones'                 : ['f_index.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.033378,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.02.L': {
        'bones'                 : ['f_index.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.033378,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.03.R': {
        'bones'                 : ['f_index.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024385,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_index.03.L': {
        'bones'                 : ['f_index.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024385,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.01.R': {
        'bones'                 : ['f_middle.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053792,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.01.L': {
        'bones'                 : ['f_middle.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.053792,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.02.R': {
        'bones'                 : ['f_middle.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03347,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.02.L': {
        'bones'                 : ['f_middle.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.03347,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.03.R': {
        'bones'                 : ['f_middle.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.028028,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_middle.03.L': {
        'bones'                 : ['f_middle.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.028028,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.01.R': {
        'bones'                 : ['f_ring.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.046598,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.01.L': {
        'bones'                 : ['f_ring.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.046598,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.02.R': {
        'bones'                 : ['f_ring.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.036003,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.02.L': {
        'bones'                 : ['f_ring.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.036003,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.03.R': {
        'bones'                 : ['f_ring.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024413,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_ring.03.L': {
        'bones'                 : ['f_ring.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.024413,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.01.R': {
        'bones'                 : ['f_pinky.01.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.039485,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.01.L': {
        'bones'                 : ['f_pinky.01.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.039485,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.02.R': {
        'bones'                 : ['f_pinky.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.027034,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.02.L': {
        'bones'                 : ['f_pinky.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.027034,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.03.R': {
        'bones'                 : ['f_pinky.03.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.020288,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'f_pinky.03.L': {
        'bones'                 : ['f_pinky.03.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.020288,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'thigh.R': {
        'bones'                 : ['thigh.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.42875,
        'position_offset'       : (0, -0.04, 0),
        'adjust_rotation'       : False,
    },
    'thigh.L': {
        'bones'                 : ['thigh.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.42875,
        'position_offset'       : (0, -0.04, 0),
        'adjust_rotation'       : False,
    },
    'shin.R': {
        'bones'                 : ['shin.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.412281,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'shin.L': {
        'bones'                 : ['shin.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.412281,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'foot.R': {
        'bones'                 : ['foot.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.226,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'foot.L': {
        'bones'                 : ['foot.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.226,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'heel.02.R': {
        'bones'                 : ['heel.02.R'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.150255,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
    'heel.02.L': {
        'bones'                 : ['heel.02.L'],
        'bones_origin'          : (0, 0, 0),
        'bones_end'             : (0, 0, 0),
        'bones_length'          : 0,
        'mesh_length'           : 0.150255,
        'position_offset'       : (0, 0, 0),
        'adjust_rotation'       : False,
    },
}
